print("Fuck offf")
print("JAVA is bullshitt....")
print("Fuckk java")
print("Rohan Thakur")
print("Hello world")
print("Fuckk 2 timess")
print("Mossom thakkur")
print("Abizer is gayy")
print("Abizer takes baths once a week")
print("Rohan also follows abizer and takes bath once a week")
